import { Metadata } from "next";
import { Suspense } from "react";

import QuestionCompositionComponent from "@/components/QuestionCompositionComponent";
import QuestionCompositionSkeleton from "./QusetionCompositionSkeleton";

// Metadata
export const metadata: Metadata = {
  title: "Question Composition",
  // description: "Generated by create next app",
};

export default function QuestionComposition() {
  const breadCrumbData = [
    { name: "Home", to: "/" },
    { name: "Question Composition", to: "/question_composition" },
  ];
  
  return (
    <Suspense fallback={<QuestionCompositionSkeleton />}>
      <QuestionCompositionComponent breadCrumbData={breadCrumbData} mainText="Question Composition" preText="" subText="" type="" />
    </Suspense>
  );
}
