import { Metadata } from "next";

import BreadCrumb from "@/components/BreadCrumb";
import HeadLine2 from "@/components/HeadLine2";
import WebpageWrapper from "@/components/wrapper/WebpageWrapper";

import Image from "next/image";
import { Suspense } from "react";
import SuspenseLoader from "@/components/SuspenseLoader";

// Metadata
export const metadata: Metadata = {
  title: "Features of the jpt",
  description: "Generated by create next app",
};

export default function FeatureofJPT() {
  const breadCrumbData = [
    {
      name: "Home",
      to: "/",
    },
    {
      name: "Features of the jpt",
      to: "/features_of_the_jpt",
    },
  ];

  const features = [
    {
      title: "The Same Exam for Beginners to Advanced",
      img: "/assets/img/feature/feature-5.jpg",
      des: "The Japanese communication ability is measured by the corresponding JPT test, so everyone from N5 to N4 level students can apply for the same test.",
    },
    {
      title: "Exam results are expressed in marks",
      img: "/assets/img/feature/feature-2.jpg",
      des: "The test results are not expressed by passing or failing.Total 200 marks exam.According to the obtained marks it will be counted JLPT N5/N4 level.",
    },
    {
      title: "Measure communication skills",
      img: "/assets/img/feature/feature-1.jpg",
      des: "JPT test cover a wide range of topics (Upto N5-N5 level) from everyday life to basic business situations, it is possible to measure the communication skills required for multiple language use scenarios.",
    },
    {
      title: "Can take the test repeatedly",
      img: "/assets/img/feature/feature-6.jpg",
      des: "Exams are held at a frequency of approximately once a month for the convenience of candidates. Because it is the same difficulty every time, you can measure your progress by taking the test repeatedly.",
    },
    {
      title: "Exams that require quick answers",
      img: "/assets/img/feature/feature-4.jpg",
      des: "Since it is an exam that requires quick answers, it is possible to measure true communication skills.",
    },
    {
      title: "Points are represented by point equivalence",
      img: "/assets/img/feature/feature-3.jpg",
      des: "The scores are expressed in the same way as a score equal to 200 out of 200.",
    },
  ];
  return (
    <Suspense fallback={<SuspenseLoader />}>
      <div className="mt-5 pb-15">
        <WebpageWrapper>
          <BreadCrumb breadCrumbData={breadCrumbData} />
          <div className="sm:w-1/2 mt-5">
            <HeadLine2
              mainText="Features of JPT"
              preText="See all the"
              subText=""
            />
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5 lg:gap-10 mt-10 lg:mb-15">
            {features.map((feature, index) => (
              <div
                key={index}
                className={`rounded-2xl overflow-hidden drop-shadow-md shadow-lg hover:shadow-2xl transition-shadow duration-300 bg-white ${
                  index == 1 || index == 4 ? "lg:translate-y-10" : ""
                }`}
              >
                <div className="w-full h-[200px]">
                  <Image
                    src={feature.img}
                    alt="JPT Exam"
                    width={404}
                    height={204}
                    className="w-full h-full object-cover"
                  />
                </div>
                <div className="p-6">
                  <h2 className="text-xl font-semibold primary-text-color mb-2">
                    {feature.title}
                  </h2>
                  <p className="text-gray-600 text-sm leading-relaxed">
                    {feature.des}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </WebpageWrapper>
      </div>
    </Suspense>
  );
}
