import { Metadata } from "next";

import BreadCrumb from "@/components/BreadCrumb";
import HeadLine2 from "@/components/HeadLine2";
import WebpageWrapper from "@/components/wrapper/WebpageWrapper";
import SampleQuestionWrapper from "@/components/SampleQuestion/SampleQuestionWrapper";
import { Suspense } from "react";
import SuspenseLoader from "@/components/SuspenseLoader";

// Metadata
export const metadata: Metadata = {
  title: "Sample Question",
  description: "Generated by create next app",
};

export default function SampleQuestion() {
  const breadCrumbData = [
    {
      name: "Home",
      to: "/",
    },
    {
      name: "Sample Question",
      to: "/sample_question",
    },
  ];
  return (
    <Suspense fallback={<SuspenseLoader />}>
      <div className="space-y-15 pb-15 pt-5">
        <WebpageWrapper>
          <BreadCrumb breadCrumbData={breadCrumbData} />
          <div className="sm:w-2/3 mt-5">
            <HeadLine2
              mainText="Sample Question"
              preText="See all the"
              subText=""
            />
          </div>
          <SampleQuestionWrapper />
        </WebpageWrapper>
      </div>
    </Suspense>
  );
}
