import { Metadata } from "next";
import { Suspense } from "react";

import SuspenseLoader from "@/components/SuspenseLoader";
import QuestionCompositionComponent from "@/components/QuestionCompositionComponent";

// Metadata
export const metadata: Metadata = {
  title: "Question Composition",
  description: "Generated by create next app",
};

export default function QuestionComposition() {
  const breadCrumbData = [
    { name: "Home", to: "/" },
    { name: "Question Composition", to: "/question_composition" },
  ];
  
  return (
    <Suspense fallback={<SuspenseLoader />}>
      <QuestionCompositionComponent breadCrumbData={breadCrumbData} mainText="Question Composition" preText="" subText=""/>
    </Suspense>
  );
}
