import BreadCrumb from "@/components/BreadCrumb";
import HeadLine2 from "@/components/HeadLine2";
import SuspenseLoader from "@/components/SuspenseLoader";
import WebpageWrapper from "@/components/wrapper/WebpageWrapper";
import { Suspense } from "react";

// Metadata
export const metadata = {
  title: "Terms & condition",
  description: "Generated by create next app",
};

export default function TOC() {
  const breadCrumbData = [
    {
      name: "Home",
      to: "/",
    },
    {
      name: "Terms & condition",
      to: "/terms_condition",
    },
  ];
  return (
    <Suspense fallback={<SuspenseLoader />}>
      <div className="pt-5 pb-15">
        <WebpageWrapper>
          <BreadCrumb breadCrumbData={breadCrumbData} />
          <div className="w-2/3 mt-5">
            <HeadLine2
              mainText="Terms & Condition"
              preText="See our"
              subText=""
            />
          </div>
          <div className="bg-white mt-10 space-y-15 text-gray-700 leading-relaxed">
            {/* General Notes Section */}
            <div>
              <h2 className="text-3xl font-bold text-blue-700 border-l-4 border-blue-500 pl-4 mb-6">
                General Notes on Taking the Test
              </h2>
              <div className="bg-white p-8 rounded-3xl shadow-xl border border-gray-100 space-y-10">
                <ol className="list-decimal list-inside space-y-6 text-[16px] text-gray-800">
                  <li>
                    <strong>Once you apply</strong>, we cannot change the exam
                    date, examinee, or refund your fee.
                  </li>

                  <li>
                    Entry is allowed <strong>only after registration</strong>.
                    <p className="mt-2">
                      Also, you <strong>must bring a valid photo ID</strong> to
                      sit for the exam.
                    </p>
                    {/* ID Card Box */}
                    <div className="border-l-4 border-blue-500 bg-blue-50 p-5 rounded-lg mt-4">
                      <p className="font-semibold text-gray-800">
                        ✅ Accepted IDs
                        <span className="block text-sm font-normal text-gray-600 mt-1">
                          (Must be a valid photo ID issued in Bangladesh)
                        </span>
                      </p>
                      <ul className="list-disc pl-5 mt-2 text-sm space-y-1">
                        <li>National ID Card (NID)</li>
                        <li>Student ID</li>
                        <li>Passport</li>
                        <li>Driver’s License</li>
                      </ul>
                    </div>
                    <p className="mt-4 text-sm text-red-600 italic">
                      *Original ID only. Photocopies not accepted. No refund if
                      disqualified due to ID issues.
                    </p>
                  </li>

                  <li>
                    <strong>Devices:</strong> Turn off all electronic devices
                    (phones, PCs, etc.) during the exam.
                  </li>

                  <li>
                    <strong>Smoking:</strong> Only allowed in designated areas.
                    Follow all proctor instructions.
                  </li>

                  <li>
                    <strong>No food or drinks</strong> allowed in the test room.
                  </li>

                  <li>
                    <strong>Bring a wristwatch</strong> as there will be no
                    clock in the exam room.
                  </li>

                  <li>
                    <span className="text-red-600 font-bold text-[16px]">
                      🚫 Strictly Prohibited Actions:
                    </span>
                    <p className="mt-2 text-sm text-red-600 font-medium">
                      Violation may result in disqualification and your exam
                      will not be scored.
                    </p>

                    <ol className="list-decimal list-inside ml-6 mt-4 space-y-4 text-[15px]">
                      <li>
                        Recording (photo/video/audio) or copying test content
                      </li>
                      <li>Writing outside allowed spaces</li>
                      <li>Removing or sharing test materials</li>
                      <li>Publishing any test content (online or offline)</li>
                      <li>
                        Getting help from others:
                        <ul className="list-disc ml-6 mt-2 space-y-1 text-gray-700">
                          <li>Using unauthorized materials</li>
                          <li>Sending a substitute test taker</li>
                          <li>Talking or receiving help</li>
                          <li>Any dishonest behavior</li>
                        </ul>
                      </li>
                      <li>
                        Overstaying allotted time:
                        <ul className="list-disc ml-6 mt-2 space-y-1 text-gray-700">
                          <li>Answering before or after official time</li>
                        </ul>
                      </li>
                      <li>Acts of sabotage or disruption</li>
                    </ol>
                  </li>
                </ol>
              </div>
            </div>

            <div className="mt-10 ">
              <h2 className="text-3xl font-extrabold text-blue-700 border-l-4 border-blue-500 pl-4 mb-8">
                Rules for dealing with misconduct
              </h2>

              <div className="bg-white p-8 rounded-3xl shadow-xl border border-gray-100 space-y-10">
                {[
                  {
                    title: "Article One (Purpose)",
                    content:
                      "This provision is intended to ensure fair evaluation of the JPT (Japanese Proficiency Test), which is conducted by the Japanese Language Proficiency Test Implementation Committee.",
                  },
                  {
                    title: "Article Two (Effectiveness)",
                    content:
                      "This provision will be the basis for official judgments and decisions of the Committee in the event of any disputes or issues arising from fraudulent conduct.",
                  },
                  {
                    title: "Article Three (Definition of Fraud)",
                    content:
                      "Cheating refers to any act that interferes with fair examination evaluation—such as taking help from others or using dishonest means to score higher than one's actual ability.",
                  },
                  {
                    title: "Article Four (Discovery of Misconduct)",
                    content: (
                      <ul className="space-y-4 list-disc list-inside text-gray-700">
                        <li>
                          <span className="font-semibold text-blue-700">
                            On-site detection:
                          </span>{" "}
                          Examiners are forced to leave the room after
                          submitting their answer sheets and question papers due
                          to cheating detected at the examination site by the
                          proctors and test facilitators.
                        </li>
                        <li>
                          <span className="font-semibold text-blue-700">
                            Post-facto Detection:
                          </span>{" "}
                          During the grade processing process, examinees who are
                          highly likely to have committed fraud, such as when
                          their answers are highly similar to others will be
                          categorized as grade notification pending students.{" "}
                          <br /> In addition, the announcement of grades and the
                          issuance of transcripts for that students will be
                          suspended until the reason for the suspension
                          disappears.
                        </li>
                        <li>
                          <span className="font-semibold text-blue-700">
                            Proxy Exams:
                          </span>{" "}
                          Such as a fraudulent act by a person who is pretending
                          to be the examinee, or exchanging answer sheets with
                          others at this time, all persons who are involved in
                          this act will be treated as dishonest performers.
                        </li>
                        <li>
                          <span className="font-semibold text-blue-700">
                            Others:
                          </span>{" "}
                          It refers other any types of misconduct except
                          mentioned above 1,2 and 3.
                        </li>
                      </ul>
                    ),
                  },
                  {
                    title:
                      "Article Five (Disposal of Misconduct and Disqualification)",
                    content: (
                      <ul className="list-disc list-inside space-y-2 text-gray-700 text-[15px]">
                        <li>
                          Civil or criminal penalties for misconduct:
                          disqualification for 5 years
                        </li>
                        <li>
                          Acts of falsifying identification cards, handbooks for
                          persons with disabilities, etc. to take examinations:
                          Disqualification of examination eligibility for four
                          years
                        </li>
                        <li>
                          Acts of forging and using transcripts at home and
                          abroad: disqualification for 4 years
                        </li>
                        <li>
                          Acts that fall under the substitute examination:
                          deprivation of eligibility for examination for 4 years
                        </li>
                        <li>
                          Acts of taking notes or recording questions:
                          disqualification for 4 years
                        </li>
                        <li>
                          Acts of leaking, printing or distributing part or all
                          of the questions: disqualification for 4 years
                        </li>
                        <li>
                          Acts of sending and receiving answers using
                          communication devices (mobile phones, etc.):
                          disqualification for 4 years
                        </li>
                        <li>
                          Acts of looking at other people’s answers during an
                          exam or showing your own answers to others:
                          disqualification for taking the exam for 2 years
                        </li>
                      </ul>
                    ),
                  },
                  {
                    title: "Article Six (Copyright Infringement)",
                    content: (
                      <ul className="list-disc list-inside space-y-2 text-gray-700 text-[15px]">
                        <li>
                          Act of recording, filming part or all of the question:
                          disqualification for 4 years
                        </li>
                        <li>
                          Acts of leaking, printing, distributing, lecturing
                          online and offline part or all of the questions:
                          disqualification for 4 years
                        </li>
                      </ul>
                    ),
                  },
                  {
                    title:
                      "Article Seven (Follow-up for Misconduct or Infringement)",
                    content: (
                      <div className="space-y-6 text-gray-700 text-[15px]">
                        <div>
                          <h3 className="text-blue-700 font-semibold mb-1">
                            Fraudster Follow-up:
                          </h3>
                          <ul className="list-disc list-inside ml-4 space-y-1">
                            <li>Invalidation of grades</li>
                            <li>
                              Disqualification for 2 to 5 years from the date of
                              misconduct
                            </li>
                            <li>
                              Send a misconduct report to the head of the
                              examinee ‘s affiliated organization (limited to IP
                              exams)
                            </li>
                          </ul>
                        </div>
                        <div>
                          <h3 className="text-blue-700 font-semibold mb-1">
                            Copyright Infringer:
                          </h3>
                          <ul className="list-disc list-inside ml-4 space-y-1">
                            <li>Invalidation of grades</li>
                            <li>
                              Deprivation of eligibility of examination for 4
                              years from the time of occurrence
                            </li>
                            <li>Civil and criminal measures</li>
                            <li>
                              Send a misconduct report to the head of the
                              examinee ‘s affiliated organization (limited to IP
                              exams)
                            </li>
                          </ul>
                        </div>
                      </div>
                    ),
                  },
                  {
                    title: "Article Eight (Retest)",
                    content: (
                      <ul className="list-disc list-inside space-y-2 text-gray-700 text-[15px]">
                        <li>
                          Applicants whose results have been withheld based on
                          Article 4, Item 2 for fraudulent act, under these
                          regulations they must retest within two months from
                          the last day of the month in which the fact was
                          notified and their test results will be disqualified
                          due to fraud. Actually, you have to prove that you
                          didn’t do it.
                        </li>
                        <li>
                          If the retest result is less than 50 points lower than
                          the test result, it will be treated as normal, and if
                          it exceeds 50 points, it will be treated as cheating.
                          Re – examination will be done separately for listening
                          evaluation and reading evaluation depending on
                          similarity and score deviation.
                        </li>
                        <li>
                          The retest results will be used as a basis for
                          handling misconduct.
                        </li>
                        <li>
                          Even if an examinee obtains grades after the
                          announcement of grades, if cheating is found during
                          the post-fact investigation process, the grades and
                          all grades obtained after that will be invalidated.
                          Articles 5 and 7 shall apply to disqualification and
                          follow-up measures.
                        </li>
                      </ul>
                    ),
                  },
                  {
                    title: "Article Nine (Retest Process)",
                    content: (
                      <ul className="list-disc list-inside space-y-2 text-gray-700 text-[15px]">
                        <li>
                          he Committee is obliged to notify retest candidates
                          that retesting will be conducted pursuant to Article
                          8, Paragraph 1.
                        </li>
                        <li>
                          Re-examiners may take the exam after signing the
                          re-examination consent form. A signed agreement is
                          legally binding and cannot be reversed.
                        </li>
                        <li>
                          The examination time will conform with the regular
                          examination period.
                        </li>
                        <li>
                          For retesting, use the specified question form by the
                          Committee.
                        </li>
                        <li>
                          Candidates can take the re-examination at the regular
                          examination center which is established by the
                          Committee Headquarters or if it is not available, they
                          can take the regular examination during the
                          re-examination period. If you take the test at the
                          test center, you will be notified within 8 days after
                          the test date, and if you take the regular test, you
                          will be notified within 3 days based on the business
                          day after the result announcement.
                        </li>
                        <li>
                          The detection of misconduct during the re- examination
                          process will be in accordance with these regulations.
                        </li>
                        <li>
                          If there is a reason why the retaker cannot retake the
                          test within two months from the last day of the month
                          in which he or she received the notice of suspension
                          of results, the test may be postponed once within 30
                          days upon submission of proof can be done.
                        </li>
                        <li>
                          Retester may appeal the retest results as well as
                          retest process. If the committee think that the
                          retester ‘s objection is valid, the committee will
                          allow one additional retest. Additional retests are
                          conducted in the same manner as retests where the
                          retester cannot appeal the results of additional
                          retests.
                        </li>
                      </ul>
                    ),
                  },
                  {
                    title: "Article Ten (Response to Retest Refusal)",
                    content:
                      "Candidates who fall under Article 8, Paragraph 1 of these regulations and do not retake the examination without justifiable reason from the date of notification of the retest requested by the Committee to the implementation date of the regular examination two months after the next month will be treated as a misconduct person.",
                  },
                ].map((article, idx) => (
                  <div key={idx} className="space-y-3">
                    <h3 className="text-xl font-bold">{article.title}</h3>
                    <div className="text-sm text-gray-800">
                      {article.content}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Responses to Violations Section */}
            <div>
              <h2 className="text-3xl font-bold text-blue-700 border-l-4 border-blue-500 pl-4 mb-6">
                Responses to Violations
              </h2>
              <div className="bg-white p-8 rounded-3xl shadow-xl border border-gray-100 space-y-8">
                <ol className="list-decimal list-inside space-y-6 text-[16px]">
                  <li>
                    <strong>If you engage in any prohibited acts</strong> or if
                    there's doubt about your answer authenticity, the following
                    may apply:
                    <ul className="list-disc pl-6 mt-3 space-y-2 text-sm text-gray-700">
                      <li>Verbal warning or dismissal from the test center</li>
                      <li>Inspection of personal belongings</li>
                      <li>Your answers may not be scored</li>
                      <li>Disqualification from the test</li>
                      <li>Cancellation of test results</li>
                    </ul>
                  </li>
                  <li>
                    <strong>Proctors may move around</strong> to monitor
                    behavior and ensure fairness.
                  </li>
                </ol>
              </div>
            </div>

            {/* Cancellations Section */}
            <div>
              <h2 className="text-3xl font-bold text-blue-700 border-l-4 border-blue-500 pl-4 mb-6">
                Important Notice on Test Cancellations
              </h2>
              <div className="bg-white p-8 rounded-3xl shadow-xl border border-gray-100 space-y-5 text-[15px]">
                <p>
                  We may cancel or postpone the test in the event of
                  uncontrollable circumstances such as:
                </p>
                <ul className="list-disc pl-6 space-y-1 text-sm text-gray-700">
                  <li>Natural disasters</li>
                  <li>Public disturbances or strikes</li>
                  <li>Outbreaks of disease</li>
                  <li>Transport or blackout issues</li>
                  <li>Network or communication failures</li>
                </ul>
                <p>
                  If the exam is postponed, it will be rescheduled on the next
                  public test date. Only the test fee will be carried forward.
                </p>
                <p className="text-sm text-red-600 italic">
                  ※ We are not liable for personal losses, travel costs, or
                  inconvenience caused by cancellation/postponement.
                </p>
              </div>
            </div>
          </div>
        </WebpageWrapper>
      </div>
    </Suspense>
  );
}
