import { Metadata } from "next";

import BreadCrumb from "@/components/BreadCrumb";
import HeadLine2 from "@/components/HeadLine2";
import JPTCollegeCompany from "@/components/ListOfCollegesAndCompaniesAcceptJPT/JPTCollegeCompany";
import WebpageWrapper from "@/components/wrapper/WebpageWrapper";
import { Suspense } from "react";
import SuspenseLoader from "@/components/SuspenseLoader";

// Metadata
export const metadata: Metadata = {
  title: "List of colleges and companies accept JPT",
  description: "Generated by create next app",
};

export default function ListOfCollege() {
  const breadCrumbData = [
    {
      name: "Home",
      to: "/",
    },
    {
      name: "List of colleges and companies accept JPT",
      to: "/list_of_colleges_and_companies_admitted_to_jpt",
    },
  ];
  return (
    <Suspense fallback={<SuspenseLoader />}>
      <div className="space-y-15 pb-15 pt-5">
        <WebpageWrapper>
          <BreadCrumb breadCrumbData={breadCrumbData} />
          <div className="sm:w-2/3 mt-5">
            <HeadLine2
              mainText="Colleges and companies accept JPT"
              preText="See all the list of"
              subText=""
            />
          </div>
          <div className="mt-10">
            <JPTCollegeCompany />
          </div>
        </WebpageWrapper>
      </div>
    </Suspense>
  );
}
