import { Metadata } from "next";
import FAQ from "./faqPage";
import { Suspense } from "react";
import SuspenseLoader from "@/components/SuspenseLoader";

export const metadata: Metadata = {
  title: "FAQ",
  description: "Generated by create next app",
};

interface FAQ {
  id: null | number;
  question: string;
  answer: string;
}

const getFaqList = async (): Promise<FAQ[]> => {
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_BASE_URL}/faq/list`, {
    cache: "no-store",
  });
  if (!res.ok) throw new Error("Failed to fetch centers");
  const data = await res.json();
  return data?.data || [];
};

export default async function FaqPageWrapper() {
  const faqs = await getFaqList();
  return (
    <Suspense fallback={<SuspenseLoader />}>
      <FAQ faqs={faqs} />
    </Suspense>
  );
}
