import SuspenseLoader from "@/components/SuspenseLoader";
import { Suspense } from "react";
import TermsConditionComponent from "./TermsConditionComponent";

// Metadata
export const metadata = {
  title: "Terms & condition",
  description: "Generated by create next app",
};

export default function TOC() {
  return (
    <Suspense fallback={<SuspenseLoader />}>
      <TermsConditionComponent />
    </Suspense>
  );
}
