import type { Metadata } from "next";
import { Suspense } from "react";

// Components
import BreadCrumb from "@/components/BreadCrumb";
import HeadLine2 from "@/components/HeadLine2";
import WebpageWrapper from "@/components/wrapper/WebpageWrapper";
import SuspenseLoader from "@/components/SuspenseLoader";

// Metadata
export const metadata: Metadata = {
  title: "About Hashira",
  description: "Generated by create next app",
};

export default function AboutJPT() {
  const breadCrumbData = [
    { name: "Home", to: "/" },
    { name: "About Mock Test", to: "/about_jpt" },
  ];
  return (
    <>
      <Suspense
        fallback={
         <SuspenseLoader/>
        }
      >
        <div className="pt-5">
          <WebpageWrapper>
            <BreadCrumb breadCrumbData={breadCrumbData} />
            <div className="w-1/2 mt-5">
              <HeadLine2 mainText="About Mocktest" preText="" subText="" />
            </div>
            <div className="mt-10 pb-15 space-y-15 ">
              {/* JPT Description Section */}
                <div className="space-y-5 text-gray-700 sm:text-lg leading-relaxed">
                <p>
                  <span className="font-semibold text-blue-700">
                  The JPT (Japanese Proficiency Test)
                  </span>{" "}
                  is a Japanese language certification recognized by the
                  Ministry of Justice Immigration Services Agency of Japan.
                </p>
                <p>
                  This site helps you prepare for Japanese language exams such as{" "}
                  <span className="font-medium text-green-600">JPT</span> and{" "}
                  <span className="font-medium text-green-600">JLPT</span> with mock tests and resources.
                </p>
                <p>
                  <span className="font-medium text-green-600">
                  JPT Score 68+
                  </span>{" "}
                  is equivalent to{" "}
                  <span className="font-medium text-green-600">JLPT-N5</span>
                </p>
                <p>
                  <span className="font-medium text-green-600">
                  JPT Score 89+
                  </span>{" "}
                  is equivalent to{" "}
                  <span className="font-medium text-green-600">JLPT-N4</span>
                </p>
                <p>
                  The JPT aims to objectively measure and evaluate advanced and
                  functional communication skills for daily and business life in
                  Japanese.
                </p>
                </div>

              {/* JPT Info Cards Section */}
              {/* <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">
                {[
                  {
                    img: "/assets/img/about/about-jpt-3.jpg",
                    to: "/list_of_colleges_and_companies_admitted_to_jpt",
                    lable: "Schools and companies accept JPT",
                  },
                  {
                    img: "/assets/img/about/about-jpt-1.jpg",
                    to: "/features_of_the_jpt",
                    lable: "Features of the JPT",
                  },
                  {
                    img: "/assets/img/about/about-jpt-4.jpg",
                    to: "/score_descriptions",
                    lable: "Score Descriptions of JPT",
                  },
                  {
                    img: "/assets/img/about/about-jpt-2.jpg",
                    to: "/differences_between_the_jpt_and_jlpt",
                    lable: "Differences between JLPT & JPT",
                  },
                ].map((item, index) => (
                  <a
                    key={index}
                    href={item.to}
                    className="group block bg-white rounded-2xl overflow-hidden border border-gray-200 shadow hover:shadow-xl transition duration-300"
                  >
                    <div className="overflow-hidden">
                      <img
                        src={item.img}
                        alt={item.lable}
                        className="w-full h-48 object-cover group-hover:scale-105 transition-transform duration-300"
                      />
                    </div>
                    <div className="p-4 text-center">
                      <p className="font-semibold text-gray-800 group-hover:text-blue-700 transition-colors duration-300">
                        {item.lable}
                      </p>
                    </div>
                  </a>
                ))}
              </div> */}
            </div>
          </WebpageWrapper>
        </div>
      </Suspense>
    </>
  );
}
