import type { Metadata } from "next";
import { Suspense } from "react";

// Components
import BreadCrumb from "@/components/BreadCrumb";
import HeadLine2 from "@/components/HeadLine2";
import WebpageWrapper from "@/components/wrapper/WebpageWrapper";
import SuspenseLoader from "@/components/SuspenseLoader";

// Metadata
export const metadata: Metadata = {
  title: "About Hashira",
  description: "Generated by create next app",
};

export default function AboutJPT() {
  const breadCrumbData = [
    { name: "Home", to: "/" },
    { name: "About Mock Test", to: "/about_jpt" },
  ];
  return (
    <>
      <Suspense
        fallback={
         <SuspenseLoader/>
        }
      >
        <div className="pt-5">
          <WebpageWrapper>
            <BreadCrumb breadCrumbData={breadCrumbData} />
            <div className="w-1/2 mt-5">
              <HeadLine2 mainText="About Mocktest" preText="" subText="" />
            </div>
            <div className="mt-10 pb-15 space-y-15 ">
              {/* JPT Description Section */}
                <div className="space-y-5 text-gray-700 sm:text-lg leading-relaxed">
                <p>
                  <span className="font-semibold text-blue-700">
                  The JPT (Japanese Proficiency Test)
                  </span>{" "}
                  is a Japanese language certification recognized by the
                  Ministry of Justice Immigration Services Agency of Japan.
                </p>
                <p>
                  This site helps you prepare for Japanese language exams such as{" "}
                  <span className="font-medium text-green-600">JPT</span> and{" "}
                  <span className="font-medium text-green-600">JLPT</span> with mock tests and resources.
                </p>
                <p>
                  <span className="font-medium text-green-600">
                  JPT Score 68+
                  </span>{" "}
                  is equivalent to{" "}
                  <span className="font-medium text-green-600">JLPT-N5</span>
                </p>
                <p>
                  <span className="font-medium text-green-600">
                  JPT Score 89+
                  </span>{" "}
                  is equivalent to{" "}
                  <span className="font-medium text-green-600">JLPT-N4</span>
                </p>
                <p>
                  The JPT aims to objectively measure and evaluate advanced and
                  functional communication skills for daily and business life in
                  Japanese.
                </p>
                </div>
            </div>
          </WebpageWrapper>
        </div>
      </Suspense>
    </>
  );
}
