import { Metadata } from "next";

import BreadCrumb from "@/components/BreadCrumb";
import HeadLine2 from "@/components/HeadLine2";
import WebpageWrapper from "@/components/wrapper/WebpageWrapper";
import { Suspense } from "react";
import SuspenseLoader from "@/components/SuspenseLoader";

// Metadata
export const metadata: Metadata = {
  title: "Recognized By Immigration Services Agency of Japan",
  description: "Generated by create next app",
};

export default function RecognizedByISA() {
  const breadCrumbData = [
    {
      name: "Home",
      to: "/",
    },
    {
      name: "Recognized By Immigration Services Agency of Japan",
      to: "/recognized_by_isa_japan",
    },
  ];
  return (
    <Suspense fallback={<SuspenseLoader />}>
      <div className="pt-5 pb-15">
        <WebpageWrapper>
          <BreadCrumb breadCrumbData={breadCrumbData} />
          <div className="sm:w-2/3 mt-5">
            <HeadLine2
              mainText="Immigration Services Agency of Japan"
              preText="Recognized By"
              subText=""
            />
          </div>
          <div className="mt-10 p-6 bg-white rounded-xl shadow-lg drop-shadow-sm space-y-4 text-gray-700 leading-relaxed">
            <p>
              The <span className="font-semibold text-blue-700">JPT</span> is a
              Japanese language proficiency test qualification recognized by the
              <span className="font-semibold text-blue-700">
                {" "}
                Ministry of Justice Immigration Services Agency of Japan
              </span>
              .
            </p>
            <p>
              It is officially accepted as a qualification to enter Japanese
              language education institutions.
            </p>
            <p>
              Scoring at least{" "}
              <span className="font-semibold text-green-700">68 points</span> or
              more on the
              <span className="font-semibold text-blue-700">
                {" "}
                JPT Elementary Exam
              </span>{" "}
              qualifies as
              <span className="font-semibold text-blue-700"> JLPT N5</span>{" "}
              level certification. The
              <span className="italic">
                {" "}
                JPT (Japanese Proficiency Test)
              </span>{" "}
              is conducted by
              <span className="font-semibold">
                {" "}
                The JPT Japan Executive Committee
              </span>
              .
            </p>
            <p>
              👉{" "}
              <a
                href="https://www.moj.go.jp/isa/applications/resources/nyuukokukanri07_00159.html"
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-600 hover:underline font-medium"
              >
                Visit the Ministry of Justice
              </a>
            </p>
          </div>
        </WebpageWrapper>
      </div>
    </Suspense>
  );
}
