import type { Metadata } from "next";
import { Suspense } from "react";
import SuspenseLoader from "@/components/SuspenseLoader";
import MockTestQuestionComposition from "./MockTestSelect";

// Metadata
export const metadata: Metadata = {
  title: "Mock test Question Composition",
  description: "Generated by create next app",
};

export default function MockTestQuestionCompositionWrapper() {
  return (
    <Suspense fallback={<SuspenseLoader />}>
      <MockTestQuestionComposition/>
    </Suspense>
  );
}
