import type { Metadata } from "next";
import { Suspense } from "react";

import MockTestQuestionComposition from "./MockTestSelect";
import QuestionCompositionSkeleton from "../../question_composition/QusetionCompositionSkeleton";

// Metadata
export const metadata: Metadata = {
  title: "Mock test Question Composition",
  description: "Generated by create next app",
};

export default function MockTestQuestionCompositionWrapper() {
  return (
    <Suspense fallback={<QuestionCompositionSkeleton />}>
      <MockTestQuestionComposition/>
    </Suspense>
  );
}
