import { Metadata } from "next";

import BreadCrumb from "@/components/BreadCrumb";
import HeadLine2 from "@/components/HeadLine2";
import WebpageWrapper from "@/components/wrapper/WebpageWrapper";
import HomeLocation from "@/components/home/HomeLocation";

import Image from "next/image";
import { Suspense } from "react";
import SuspenseLoader from "@/components/SuspenseLoader";

// Metadata
export const metadata: Metadata = {
  title: "Exam Center In Bangladesh",
  description: "Generated by create next app",
};

export default function ExamCenter() {
  const breadCrumbData = [
    {
      name: "Home",
      to: "/",
    },
    {
      name: "Exam Center In Bangladesh",
      to: "/exam_center",
    },
  ];
  return (
    <Suspense fallback={<SuspenseLoader />}>
      <div className="space-y-15 pb-15 pt-5">
        <WebpageWrapper>
          <BreadCrumb breadCrumbData={breadCrumbData} />
          <div className="mt-5 flex items-center">
            <div className="md:w-2/3 xl:w-1/2 h-fit md:bg-[#f6fafdf1] md:p-8 rounded-xl md:-mr-20 relative z-10 md:shadow-xl md:drop-shadow-md">
              <HeadLine2
                preText="See our locations"
                mainText="All Over In Bangladesh"
                subText="Mock test exams in Bangladesh are held at the Institute of Modern Languages, University of Dhaka, offering a prestigious and high-standard testing environment."
              />
            </div>
            <div className="hidden md:block w-full md:w-[800px] max-h-[60vh] overflow-hidden">
              <Image
                src="/assets/img/exam/exam.jpg"
                width={1920}
                height={1080}
                alt=""
                className="w-full max-h-[60vh] object-cover object-bottom"
              />
            </div>
          </div>
        </WebpageWrapper>
        <HomeLocation />
      </div>
    </Suspense>
  );
}
