import { Metadata } from "next";

import BreadCrumb from "@/components/BreadCrumb";
import HeadLine from "@/components/HeadLine";
import HomeRegistration from "@/components/home/RegistrationSection";
import WebpageWrapper from "@/components/wrapper/WebpageWrapper";
import { Suspense } from "react";
import SuspenseLoader from "@/components/SuspenseLoader";

// Metadata
export const metadata: Metadata = {
  title: "Registration",
  description: "Generated by create next app",
};

export default function Registration() {
  const breadCrumbData = [
    {
      name: "Home",
      to: "/",
    },
    {
      name: "Registration",
      to: "/registration",
    },
  ];

  return (
    <Suspense fallback={<SuspenseLoader />}>
      <div className="pb-15">
        <WebpageWrapper>
          <BreadCrumb breadCrumbData={breadCrumbData} />
          <HeadLine mainText="Registration" preText="" subText="" />
        </WebpageWrapper>
        <HomeRegistration />
      </div>
    </Suspense>
  );
}
