import { Metadata } from "next";

import BreadCrumb from "@/components/BreadCrumb";
import HeadLine2 from "@/components/HeadLine2";
import WebpageWrapper from "@/components/wrapper/WebpageWrapper";
import { Suspense } from "react";
import SuspenseLoader from "@/components/SuspenseLoader";

// Metadata
export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Generated by create next app",
};

export default function PrivacyPolicy() {
  const breadCrumbData = [
    {
      name: "Home",
      to: "/",
    },
    {
      name: "Privacy Policy",
      to: "/privacy_policy",
    },
  ];
  return (
    <Suspense fallback={<SuspenseLoader />}>
      <div className="pt-5 pb-15">
        <WebpageWrapper>
          <BreadCrumb breadCrumbData={breadCrumbData} />
          <div className="w-2/3 mt-5">
            <HeadLine2 mainText="Privacy Policy" preText="See our" subText="" />
          </div>
          <div className="bg-white mt-10 space-y-10">
            {[
              {
                title: "Introduction",
                content: (
                  <p>
                    This privacy policy (“Privacy Policy”) explains how{" "}
                    <strong className="text-blue-700">JPT-BD</strong> (“We”)
                    handles personal data provided by you (“Customer” or “You”)
                    through websites, mobile applications, emails, and services
                    controlled by the JPT-BD team of Kaicom Solutions Japan BD.
                    Co. Ltd, Dhaka, Bangladesh.
                    <br />
                    <br />
                    We are committed to protecting your privacy and maintaining
                    the confidentiality of your data—whether you're a customer,
                    requesting info, placing orders, or contacting us. We
                    collect, process, and store your personal data for these
                    purposes.
                  </p>
                ),
              },
              {
                title: "Privacy Policy Statement",
                content: (
                  <p>
                    JPT Exams (
                    <a
                      href="https://jptbd.com"
                      className="text-blue-600 underline hover:text-blue-800 transition"
                    >
                      https://jptbd.com
                    </a>
                    ) is operated by Kaicom Solutions Japan Bd. Ltd. (JPT EXAMS
                    TEAM). We support, consult, and offer online education for
                    Bangladeshi candidates preparing for the JPT exam. Your
                    privacy and data are important to us.
                  </p>
                ),
              },
              {
                title: "Personal Data",
                content: (
                  <ul className="list-disc list-inside space-y-2">
                    <li>
                      Data is collected with consent and a stated purpose.
                    </li>
                    <li>Usage is limited to specified purposes only.</li>
                    <li>
                      Outsourced work follows strict confidentiality policies.
                    </li>
                    <li>
                      No sharing with third parties without explicit consent.
                    </li>
                  </ul>
                ),
              },
              {
                title: "Purpose of Collecting Personal Data",
                content: (
                  <>
                    <p>
                      We collect personal data to deliver JPT services and
                      communicate effectively.
                    </p>
                    <p className="mt-2">This includes:</p>
                    <ul className="list-disc list-inside space-y-2 mt-1">
                      <li>Grading answers and test development</li>
                      <li>Issuing/reissuing exam tickets and results</li>
                      <li>Sending test updates and business-related content</li>
                      <li>
                        Analyzing test results and preparing documentation
                      </li>
                      <li>Providing learning materials and resources</li>
                      <li>Recruiting JPT test proctors</li>
                      <li>Publishing committee newsletters and info</li>
                    </ul>
                  </>
                ),
              },
              {
                title: "Provision of Personal Data to a Foreign Third Party",
                content: (
                  <p>
                    Personal data may be shared with Freemind Co. Ltd. / The JPT
                    Japan Executive Committee (Kyoto, Japan) for grading
                    purposes, only with your consent. Overseas transcript
                    requests may also result in data transfer to designated
                    agencies.
                  </p>
                ),
              },
              {
                title: "SSL (Secure Socket Layer)",
                content: (
                  <p>
                    The JPTBD site uses SSL encryption to protect your submitted
                    data from external interception and ensure secure
                    communication.
                  </p>
                ),
              },
              {
                title: "Cookies",
                content: (
                  <p>
                    We may use cookies to remember user preferences and maintain
                    session state for improved user experience.
                  </p>
                ),
              },
              {
                title: "JPTBD on Social Media",
                content: (
                  <p>
                    We maintain social media profiles (e.g., Facebook, LinkedIn,
                    Twitter). We do not track or collect data via social
                    platforms or embedded social buttons. Platform interaction
                    requires users to visit our profiles directly.
                  </p>
                ),
              },
              {
                title: "Exclusions of Liability",
                content: (
                  <>
                    <p>
                      Use of our site is at your own risk. We do not guarantee
                      safety from:
                    </p>
                    <ul className="list-disc list-inside space-y-1 mt-1">
                      <li>Viruses, spyware, or malware</li>
                      <li>Data loss or unauthorized third-party changes</li>
                    </ul>
                  </>
                ),
              },
              {
                title: "Changes to this Privacy Policy",
                content: (
                  <p>
                    JPTBD reserves the right to update this policy at any time.
                    Changes will be reflected with an effective date. We may
                    notify users through newsletters, emails, or social media.
                    Please review regularly.
                  </p>
                ),
              },
            ].map((section, idx) => (
              <div key={idx} className="space-y-3 animate-fade-in">
                <h2 className="text-2xl font-bold text-blue-700 border-l-4 border-blue-500 pl-4">
                  {section.title}
                </h2>
                <div className="text-[17px] text-gray-700">
                  {section.content}
                </div>
              </div>
            ))}
          </div>
        </WebpageWrapper>
      </div>
    </Suspense>
  );
}
