import type { Metadata } from "next";

// Next.js built-in imports
import Image from "next/image";
import Link from "next/link";

// External libraries
import axios from "axios";

// Components
import BreadCrumb from "@/components/BreadCrumb";
import HeadLine2 from "@/components/HeadLine2";
import WebpageWrapper from "@/components/wrapper/WebpageWrapper";
import HomeRegiProcess from "@/components/home/HomeRegiProcess";
import { Suspense } from "react";
import SuspenseLoader from "@/components/SuspenseLoader";

// Metadata
export const metadata: Metadata = {
  title: "Application Procedure",
  description: "Generated by create next app",
};

// Types
interface ExamItem {
  title: string;
  description: string;
  exam_date: string;
  application_deadline: string;
  image: string;
  result_publish_date: string;
  slug: string;
  start_time: string;
  end_time: string;
  fee: string;
  available_to_apply: boolean;
}

// Data fetching
async function getExamData(): Promise<ExamItem[]> {
  try {
    const response = await axios.get(
      `${process.env.NEXT_PUBLIC_API_BASE_URL}/exam/list`
    );
    const allExams: ExamItem[] = response.data.data || [];
    return allExams;
  } catch (error) {
    console.error("Failed to fetch exam data:", error);
    return [];
  }
}

export default async function ApplicationProcedure() {
  const examData = await getExamData();

  const breadCrumbData = [
    { name: "Home", to: "/" },
    { name: "Application Procedure", to: "/application_procedure" },
  ];

  return (
    <>
      <Suspense fallback={<SuspenseLoader />}>
        <div className="space-y-15 pb-15 pt-5">
          <WebpageWrapper>
            <BreadCrumb breadCrumbData={breadCrumbData} />
            <div className="flex flex-row-reverse items-center mt-5">
              <div className="md:w-2/3 xl:w-1/2 h-fit md:bg-[#f6fafdf1] md:p-8 rounded-xl md:-ml-20 relative z-10 md:shadow-xl md:drop-shadow-md">
                <HeadLine2
                  preText="See all the"
                  mainText="Application Procedure"
                  subText="Register easily through our portal—from creating your account to preparing for exam day—ensuring a smooth path to Japanese proficiency certification."
                />
              </div>
              <div className="hidden md:block w-full md:w-[800px] max-h-[60vh] overflow-hidden">
                <Image
                  src="/assets/img/application/application.jpg"
                  width={512}
                  height={512}
                  alt=""
                  className="w-full max-h-[60vh] object-cover object-bottom"
                />
              </div>
            </div>
          </WebpageWrapper>
          <HomeRegiProcess />
          <WebpageWrapper>
            <div className="bg-white p-6 rounded-xl shadow-md mt-15">
              <ul className="space-y-4 text-sm text-gray-700">
                <li className="flex items-start gap-2">
                  <span className="text-red-500 text-lg leading-none mt-0.5">
                    ※
                  </span>
                  <span>
                    Transcripts include personal photographs. After they’ve been
                    uploaded, photos can’t be edited.
                  </span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-red-500 text-lg leading-none mt-0.5">
                    ※
                  </span>
                  <span>
                    To take this shot, it is advised that you wear clean and
                    neat attire, such as a suit.
                  </span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-red-500 text-lg leading-none mt-0.5">
                    ※
                  </span>
                  <span>
                    Images with masks and helmets, as well as photos that are
                    too tiny, will not be allowed.
                  </span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-red-500 text-lg leading-none mt-0.5">
                    ※
                  </span>
                  <span>
                    You will be unable to take the exam if the photo does not
                    match your own exam day appearance.
                  </span>
                </li>
              </ul>
            </div>

            <div className="mt-15 space-y-6">
              <div className="w-1/2">
                <HeadLine2 mainText="Process" preText="Exam Day" subText="" />
              </div>

              <p className="text-gray-700  text-sm">
                Below are the instructions for the exam day process. Candidates,
                please read carefully.
              </p>

              <div className="grid sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
                <div className="bg-gray-50  p-4 rounded-lg shadow-sm border border-gray-200 ">
                  <p className="text-gray-600  text-sm">Step - 01</p>
                  <h4 className="font-semibold text-gray-800 ">
                    10 minutes before
                  </h4>
                  <p className="text-gray-600  text-sm">
                    Check-in begins. Please arrive at the venue at least 10
                    minutes before the test instruction starts.
                  </p>
                </div>

                <div className="bg-white p-4 rounded-lg shadow-sm border border-gray-200 ">
                  <p className="text-gray-600  text-sm">Step - 02</p>
                  <h4 className="font-semibold text-gray-800 ">
                    0 – 20 minutes
                  </h4>
                  <p className="text-gray-600  text-sm">Test Instructions</p>
                </div>

                <div className="bg-gray-50  p-4 rounded-lg shadow-sm border border-gray-200 ">
                  <p className="text-gray-600  text-sm">Step - 03</p>
                  <h4 className="font-semibold text-gray-800 text-sm">
                    20 – 25 minutes
                  </h4>
                  <p className="text-gray-600  text-sm">Break Time</p>
                </div>

                <div className="bg-white p-4 rounded-lg shadow-sm border border-gray-200 ">
                  <p className="text-gray-600  text-sm">Step - 04</p>
                  <h4 className="font-semibold text-gray-800  text-sm">
                    25 – 40 minutes
                  </h4>
                  <p className="text-gray-600  text-sm">
                    Sound Check & Identification Confirmation
                  </p>
                </div>

                <div className="bg-gray-50  p-4 rounded-lg shadow-sm border border-gray-200 ">
                  <p className="text-gray-600  text-sm">Step - 05</p>
                  <h4 className="font-semibold text-gray-800  text-sm">
                    40 – 65 minutes
                  </h4>
                  <p className="text-gray-600  text-sm">
                    Listening Test (100 questions, 25 minutes)
                  </p>
                </div>

                <div className="bg-white p-4 rounded-lg shadow-sm border border-gray-200 ">
                  <p className="text-gray-600  text-sm">Step - 06</p>
                  <h4 className="font-semibold text-gray-800 text-sm">
                    65 – 90 minutes
                  </h4>
                  <p className="text-gray-600  text-sm">
                    Reading Test (100 questions, 25 minutes)
                  </p>
                </div>

                <div className="bg-gray-50  p-4 rounded-lg shadow-sm border border-gray-200">
                  <p className="text-gray-600  text-sm">Step - 07</p>
                  <h4 className="font-semibold text-gray-800 text-sm">
                    90 minutes
                  </h4>
                  <p className="text-gray-600  text-sm">
                    Exit from the test room
                  </p>
                </div>
              </div>
            </div>

            <div className="mt-15 space-y-6">
              <div className="w-full lg:w-1/2">
                <HeadLine2
                  mainText="Taking the Test"
                  preText="General Notes on"
                  subText=""
                />
              </div>

              <div className="bg-white p-5 sm:p-8 rounded-2xl shadow-2xl border border-gray-100 space-y-10">
                <ol className="list-decimal list-inside space-y-5 text-gray-900 text-[15px] leading-relaxed">
                  <li>
                    <span className="font-semibold">Once you apply</span>, we
                    cannot change the exam date, examinee, or refund your fee.
                  </li>

                  <li>
                    You may only enter the test center after completing the
                    registration form.
                    <p className="mt-2 text-gray-700">
                      Also, you{" "}
                      <span className="font-semibold">
                        must bring a valid form of ID
                      </span>{" "}
                      to sit for the exam.
                    </p>
                    <div className="border-l-4 border-blue-500 bg-blue-50 p-4 rounded-lg mt-4">
                      <p className="font-semibold text-gray-800">
                        ✅ Accepted IDs
                        <span className="text-sm font-normal block mt-1">
                          (must be a valid photo ID issued in Bangladesh)
                        </span>
                      </p>
                      <ul className="list-disc pl-5 mt-2 text-sm text-gray-700 space-y-1">
                        <li>National ID Card (NID)</li>
                        <li>Student ID</li>
                        <li>Passport</li>
                        <li>Driver’s License</li>
                      </ul>
                    </div>
                    <p className="mt-4 text-gray-600 text-sm italic">
                      *Original ID is required. No photocopies accepted. No
                      refund if disqualified due to ID issues.
                    </p>
                  </li>

                  <li>
                    <span className="font-semibold">Devices</span>: Turn off all
                    alarms and electronic devices (phones, PCs, audio players,
                    etc.) during the exam.
                  </li>

                  <li>
                    <span className="font-semibold">Smoking</span> is allowed
                    only in designated areas. Follow the proctor’s instructions
                    strictly.
                  </li>

                  <li>
                    <span className="font-semibold">No food or drinks</span>{" "}
                    allowed in the test room.
                  </li>

                  <li>
                    <span className="font-semibold">Bring a wristwatch</span>.
                    There will be no clock in the exam room.
                  </li>

                  <li>
                    <span className="text-red-600 font-bold">
                      🚫 Strictly Prohibited Actions:
                    </span>
                    <p className="mt-2 text-sm text-red-600 font-medium">
                      Violation may result in disqualification and your exam
                      will not be scored.
                    </p>

                    <div className="mt-4">
                      <ol className="list-decimal list-inside ml-6 space-y-3 text-[14px] text-gray-800">
                        <li>
                          Recording (photo/video/audio) or copying test content
                        </li>
                        <li>
                          Writing outside allowed spaces (e.g., margins, books)
                        </li>
                        <li>Removing or sharing test materials by any means</li>
                        <li>
                          Publishing or sharing any test content (online or
                          offline)
                        </li>
                        <li>
                          Getting help from others during the test
                          <ul className="list-disc ml-6 mt-2 text-gray-700 space-y-1">
                            <li>Cheating or using unauthorized materials</li>
                            <li>Sending a substitute test taker</li>
                            <li>Talking or receiving help during the test</li>
                            <li>Any dishonest behavior</li>
                          </ul>
                        </li>
                        <li>
                          Overstaying the designated time
                          <ul className="list-disc ml-6 mt-2 text-gray-700 space-y-1">
                            <li>
                              Answering before start or after time is over
                            </li>
                          </ul>
                        </li>
                        <li>
                          Acts of sabotage (violence, damage, disruption, etc.)
                        </li>
                      </ol>
                    </div>
                  </li>
                </ol>
              </div>
            </div>

            <div className="mt-15 space-y-6">
              <div className="w-full lg:w-1/2">
                <HeadLine2
                  mainText=" Violations"
                  preText="Responses to"
                  subText=""
                />
              </div>
              <div className="bg-white p-5 sm:p-8 rounded-2xl shadow-lg border border-gray-200 space-y-6">
                <ol className="list-decimal list-inside space-y-6 text-gray-900 text-[15px] leading-relaxed">
                  <li>
                    <span className="font-medium">
                      If you engage in any prohibited acts
                    </span>{" "}
                    (as mentioned above), or if there’s any suspicion about the
                    validity of your answers, the following measures may be
                    taken:
                    <ul className="list-disc pl-6 mt-3 space-y-2 text-gray-700 text-sm">
                      <li>Verbal warning or dismissal from the test site</li>
                      <li>Inspection of personal belongings</li>
                      <li>Your answers may not be scored</li>
                      <li>Disqualification from taking the test</li>
                      <li>Cancellation of test results</li>
                    </ul>
                  </li>

                  <li>
                    <span className="font-medium">
                      Proctors may move around
                    </span>{" "}
                    the test room to ensure a fair testing environment and to
                    monitor any suspicious behavior.
                  </li>
                </ol>
              </div>
            </div>

            <div className="mt-15 space-y-6">
              <div className="w-full lg:w-1/2">
                <HeadLine2
                  mainText="Cancellation or Discontinuation"
                  preText="Process of test"
                  subText=""
                />
              </div>
              <div className="bg-white p-5 sm:p-8 rounded-2xl shadow-xl border border-gray-100 space-y-4">
                <h3 className="text-lg font-semibold text-gray-800 flex items-center gap-2">
                  ⚠️ Important Notice on Test Cancellations
                </h3>
                <p className="text-[15px] leading-relaxed text-gray-700">
                  We may cancel or postpone the test in the event of
                  uncontrollable circumstances such as:
                </p>
                <ul className="list-disc pl-6 space-y-1 text-sm text-gray-600">
                  <li>Natural disasters</li>
                  <li>Strikes or public disturbances</li>
                  <li>Outbreaks of infectious diseases</li>
                  <li>Blackouts or transportation issues</li>
                  <li>Communication/network failures</li>
                </ul>
                <p className="text-[15px] text-gray-700 leading-relaxed">
                  If the exam cannot be conducted, it will be rescheduled for
                  the next public test date. Only the test fee will be carried
                  forward.
                </p>
                <p className="text-sm text-red-600 italic">
                  ※ We are not responsible for any inconvenience, costs (except
                  test fee), or personal losses resulting from cancellation or
                  postponement.
                </p>
              </div>
            </div>

            <div className="mt-15 space-y-6">
              <div className="w-full lg:w-1/2">
                <HeadLine2 mainText="Exam Details" preText="" subText="" />
              </div>
              <div className="overflow-x-auto mt-8 shadow-xl drop-shadow-md hidden lg:block">
                <table className="min-w-full border border-gray-200 rounded-xl overflow-hidden text-xs md:text-sm text-left shadow-md">
                  <thead className="bg-gradient-to-r from-blue-700 to-blue-900 text-white text-xs md:text-sm">
                    <tr>
                      <th className="px-2 py-2 sm:px-6 sm:py-4 font-semibold">
                        Title
                      </th>
                      <th className="px-2 py-2 sm:px-6 sm:py-4 font-semibold">
                        Exam Date
                      </th>
                      <th className="px-2 py-2 sm:px-6 sm:py-4 font-semibold">
                        Exam Time
                      </th>
                      <th className="px-2 py-2 sm:px-6 sm:py-4 font-semibold">
                        Application Deadline
                      </th>
                      <th className="px-2 py-2 sm:px-6 sm:py-4 font-semibold">
                        Apply
                      </th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-200">
                    {examData.map((exam, i) => (
                      <tr
                        key={i}
                        className={i % 2 === 0 ? "bg-white" : "bg-gray-50"}
                      >
                        <td className="px-2 py-2 sm:px-6 sm:py-4 text-gray-800">
                          {exam?.title}
                        </td>
                        <td className="px-2 py-2 sm:px-6 sm:py-4 text-gray-700">
                          {exam?.exam_date}
                        </td>
                        <td className="px-2 py-2 sm:px-6 sm:py-4 text-gray-700">
                          {exam?.start_time} to {exam?.end_time}
                        </td>
                        <td className="px-2 py-2 sm:px-6 sm:py-4 text-red-600">
                          {exam?.application_deadline}
                        </td>
                        <td className="px-2 py-2 sm:px-6 sm:py-4">
                          {!exam?.available_to_apply ? (
                            <button
                              disabled
                              className="bg-gray-400 hover:bg-gray-500 text-white sm:font-semibold text-xs md:text-sm py-1 px-2 sm:py-2 sm:px-4 rounded-md shadow-sm transition-all cursor-not-allowed"
                            >
                              Can't Apply
                            </button>
                          ) : (
                            <Link
                              href={`/registration_terms/${exam.slug}`}
                              className="bg-blue-600 hover:bg-blue-800 text-white sm:font-semibold text-xs md:text-sm py-1 px-2 sm:py-2 sm:px-4 rounded-md shadow-sm transition-all"
                            >
                              Apply Now
                            </Link>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              <div className="space-y-4 lg:hidden">
                {examData.map((exam, i) => (
                  <div
                    key={i}
                    className={`rounded-2xl border border-gray-200 p-6 shadow-md transition-all duration-300 ${
                      i % 2 === 0
                        ? "bg-gradient-to-br from-white via-gray-50 to-white"
                        : "bg-white"
                    } hover:shadow-lg`}
                  >
                    <h2 className="text-lg sm:text-xl font-bold text-gray-800 mb-2">
                      {exam?.title}
                    </h2>

                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 text-sm sm:text-base text-gray-700">
                      <p>
                        <span className="font-medium text-gray-900">
                          📅 Date:
                        </span>{" "}
                        {exam?.exam_date}
                      </p>
                      <p>
                        <span className="font-medium text-gray-900">
                          ⏰ Time:
                        </span>{" "}
                        {exam?.start_time} - {exam?.end_time}
                      </p>
                      <p>
                        <span className="font-medium text-gray-900">
                          🕒 Deadline:
                        </span>{" "}
                        {exam?.application_deadline}
                      </p>

                      {!exam?.available_to_apply ? (
                        <button
                          disabled
                          className="inline-block bg-gray-500 hover:bg-gray-600 text-white text-xs sm:text-sm font-semibold py-2 px-5 rounded-full shadow-sm transition-all sm:w-30 text-center"
                        >
                          Apply Now
                        </button>
                      ) : (
                        <Link
                          href={`/registration_terms/${exam.slug}`}
                          className="inline-block bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white text-xs sm:text-sm font-semibold py-2 px-5 rounded-full shadow-sm transition-all sm:w-30 text-center"
                        >
                          Apply Now
                        </Link>
                      )}
                    </div>
                  </div>
                ))}
              </div>
              <div className="bg-red-50 border-l-4 border-red-500 p-5 rounded-xl shadow-sm space-y-3 mt-10">
                <div className="flex items-start gap-2">
                  <span className="text-red-500 text-lg">⚠️</span>
                  <p className="italic text-sm text-red-700">
                    The test date and location of the test room may be altered
                    or suspended temporarily.
                  </p>
                </div>
                <div className="flex items-start gap-2">
                  <span className="text-red-500 text-lg">📅</span>
                  <p className="italic text-sm text-red-700">
                    The test results are usually available two weeks after the
                    test date.
                  </p>
                </div>
              </div>
            </div>
          </WebpageWrapper>
        </div>
      </Suspense>
    </>
  );
}
