import { Metadata } from "next";

import BreadCrumb from "@/components/BreadCrumb";
import HeadLine2 from "@/components/HeadLine2";
import WebpageWrapper from "@/components/wrapper/WebpageWrapper";
import { Suspense } from "react";
import SuspenseLoader from "@/components/SuspenseLoader";

// Metadata
export const metadata: Metadata = {
  title: "Measurement Content",
  description: "Generated by create next app",
};

export default function MeasurementContent() {
  const breadCrumbData = [
    {
      name: "Home",
      to: "/",
    },
    {
      name: "Measurement Content",
      to: "/measurement_content",
    },
  ];
  return (
    <Suspense fallback={<SuspenseLoader />}>
      <div className="pt-5">
        <WebpageWrapper>
          <BreadCrumb breadCrumbData={breadCrumbData} />
          <div className="md:w-1/2 mt-5">
            <HeadLine2 mainText="Measurement Content" preText="" subText="" />
          </div>
          <div className="mt-10 pb-15 space-y-10">
            {/* Listening Comprehension Table */}
            <div className="overflow-x-auto rounded-xl shadow-xl">
              <table className="min-w-full border-collapse text-xs sm:text-sm bg-white">
                <thead>
                  <tr className="bg-gradient-to-r from-blue-600 to-blue-800 text-white">
                    <th className="p-4 sm:p-5 text-left font-semibold border-r border-blue-200 whitespace-nowrap">
                      Constitute
                    </th>
                    <th className="p-4 sm:p-5 text-left font-semibold border-r border-blue-200 whitespace-nowrap">
                      Part
                    </th>
                    <th
                      className="p-4 sm:p-5 text-left font-semibold border-r border-blue-200 whitespace-nowrap"
                      colSpan={2}
                    >
                      Evaluation
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200">
                  <tr className="bg-gray-50">
                    <td
                      rowSpan={4}
                      className="p-4 font-semibold text-blue-700 border-r border-gray-200 align-top sm:align-middle whitespace-nowrap"
                    >
                      Listening Comprehension
                    </td>
                    <td className="p-4 border-r border-gray-200 ">
                      Statements Regarding Photographs
                    </td>
                    <td className="p-4 border-r border-gray-200" colSpan={2}>
                      Choose the most accurate statement from four spoken
                      options. Tests quick listening and comprehension.
                    </td>
                  </tr>
                  <tr className="bg-white">
                    <td className="p-4 border-r border-gray-200">
                      Question – Response
                    </td>
                    <td className="p-4 border-r border-gray-200 " colSpan={2}>
                      Listen to short conversations and pick the correct
                      response. Tests interactive communication.
                    </td>
                  </tr>
                  <tr className="bg-gray-50">
                    <td className="p-4 border-r border-gray-200 ">
                      Conversations
                    </td>
                    <td className="p-4 border-r border-gray-200" colSpan={2}>
                      Comprehend and extract general and specific details from
                      conversations.
                    </td>
                  </tr>
                  <tr className="bg-white">
                    <td className="p-4 border-r border-gray-200">Talks</td>
                    <td className="p-4 border-r border-gray-200" colSpan={2}>
                      Understand longer narratives by answering multiple
                      questions based on them.
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>

            {/* Reading Comprehension Table */}
            <div className="overflow-x-auto rounded-xl shadow-xl">
              <table className="min-w-full border-collapse text-xs sm:text-sm bg-white">
                <thead>
                  <tr className="bg-gradient-to-r from-blue-600 to-blue-800 text-white ">
                    <th className="p-4 sm:p-5 text-left font-semibold border-r border-blue-200 whitespace-nowrap">
                      Constitute
                    </th>
                    <th className="p-4 sm:p-5 text-left font-semibold border-r border-blue-200 whitespace-nowrap">
                      Part
                    </th>
                    <th
                      className="p-4 sm:p-5 text-left font-semibold border-r border-blue-200 whitespace-nowrap"
                      colSpan={2}
                    >
                      Evaluation
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200">
                  <tr className="bg-gray-50">
                    <td
                      rowSpan={4}
                      className="p-4 font-semibold text-blue-700 border-r border-gray-200 align-top sm:align-middle whitespace-nowrap"
                    >
                      Reading Comprehension
                    </td>
                    <td className="p-4 border-r border-gray-200">
                      Select Correct Answer
                    </td>
                    <td className="p-4 border-r border-gray-200" colSpan={2}>
                      Tests basic knowledge of kanji and grammar through
                      sentence creation.
                    </td>
                  </tr>
                  <tr className="bg-white">
                    <td className="p-4 border-r border-gray-200">
                      Correcting Mistakes
                    </td>
                    <td className="p-4 border-r border-gray-200" colSpan={2}>
                      Select incorrect words from options to measure grammar and
                      editing skills.
                    </td>
                  </tr>
                  <tr className="bg-gray-50">
                    <td className="p-4 border-r border-gray-200">
                      Incomplete Sentences
                    </td>
                    <td className="p-4 border-r border-gray-200" colSpan={2}>
                      Understand context and complete sentences appropriately.
                    </td>
                  </tr>
                  <tr className="bg-white">
                    <td className="p-4 border-r border-gray-200">
                      Reading Comprehension
                    </td>
                    <td className="p-4 border-r border-gray-200" colSpan={2}>
                      Evaluate ability to follow narrative flow and interpret
                      detailed expressions.
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </WebpageWrapper>
      </div>
    </Suspense>
  );
}
