import { Metadata } from "next";

import BreadCrumb from "@/components/BreadCrumb";
import HeadLine2 from "@/components/HeadLine2";
import WebpageWrapper from "@/components/wrapper/WebpageWrapper";
import { Suspense } from "react";
import SuspenseLoader from "@/components/SuspenseLoader";

// Metadata
export const metadata: Metadata = {
  title: "Refund and Cancellation",
  description: "Generated by create next app",
};

export default function Refund() {
  const breadCrumbData = [
    {
      name: "Home",
      to: "/",
    },
    {
      name: "Refund and Cancellation",
      to: "/refund_and_cancellation",
    },
  ];
  return (
    <Suspense fallback={<SuspenseLoader />}>
      <div className="pt-5 pb-15">
        <WebpageWrapper>
          <BreadCrumb breadCrumbData={breadCrumbData} />
          <div className="w-2/3 mt-5">
            <HeadLine2
              mainText="Refund and Cancellation"
              preText="See our policy of"
              subText=""
            />
          </div>
          <div className="mt-10 space-y-10">
            {[
              {
                title: "Refund Procedure",
                content: (
                  <>
                    <p>
                      A refund request will be considered valid only if it is
                      made through the{" "} website and from the email or phone number used during
                      registration, within <strong>3 days</strong> of payment.
                    </p>
                    <p className="mt-4">
                      Refunds will be processed via the same mobile financial
                      service used during payment, within{" "}
                      <strong>7 to 10 working days</strong> of approval by JPT
                      Bangladesh Customer Service. You will receive confirmation
                      via email.
                    </p>
                  </>
                ),
              },
              {
                title: "Requirements for a Valid Return",
                content: (
                  <ul className="list-disc list-inside space-y-2">
                    <li>
                      Valid proof of payment (e.g., order number or invoice)
                    </li>
                    <li>
                      A valid reason that meets our return acceptance criteria
                    </li>
                  </ul>
                ),
              },
              {
                title: "Return Not Applicable In These Cases",
                content: (
                  <ul className="list-disc list-inside space-y-2">
                    <li>Refund requests made after 3 days of payment</li>
                    <li>Fraudulent or duplicate subscriptions</li>
                    <li>Missing or invalid serial numbers</li>
                    <li>Issues caused by test taker or exam center faults</li>
                    <li>Payments cannot be cancelled once confirmed</li>
                  </ul>
                ),
              },
              {
                title: "Refund Request Conditions",
                content: (
                  <>
                    <p>
                      Refunds are only available if requested within{" "}
                      <strong>3 working days</strong> of payment. The refund
                      will be issued via the customer's bKash or mobile wallet.
                      Online gateway transaction fees will be deducted.
                    </p>
                    <ul className="list-disc list-inside mt-3 space-y-2">
                      <li>
                        If you face any inconvenience, please contact our
                        customer support team.
                      </li>
                    </ul>
                  </>
                ),
              },
            ].map((section, idx) => (
              <div key={idx} className="space-y-4 group">
                <h2 className="text-2xl sm:text-3xl font-semibold text-blue-700 flex items-center gap-2 border-l-4 border-blue-500 pl-4 group-hover:pl-5 transition-all duration-300">
                  {section.title}
                </h2>
                <div className="text-gray-700 text-[17px] leading-relaxed">
                  {section.content}
                </div>
              </div>
            ))}
          </div>
        </WebpageWrapper>
      </div>
    </Suspense>
  );
}
