import { Metadata } from "next";

import RegistrationTerm from "./registrationTermsPage";
import { Suspense } from "react";
import SuspenseLoader from "@/components/SuspenseLoader";

// Metadata
export const metadata: Metadata = {
  title: "Exam Registration Pre-screening System",
  description: "Generated by create next app",
};

export default function RegistrationTermsPageWrapper() {
  return (
    <Suspense fallback={<SuspenseLoader />}>
      <RegistrationTerm />
    </Suspense>
  );
}
