import { Metadata } from "next";

import { Suspense } from "react";
import SuspenseLoader from "@/components/SuspenseLoader";
import PrivacyPolicyComponent from "./PrivacyPolicyComponent";

// Metadata
export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Generated by create next app",
};

export default function PrivacyPolicy() {
  return (
    <Suspense fallback={<SuspenseLoader />}>
      <PrivacyPolicyComponent />
    </Suspense>
  );
}
