import type { Metadata } from "next";
import CheckoutPage from "./CheckoutPage";
import { Suspense } from "react";
import SuspenseLoader from "@/components/SuspenseLoader";

export const metadata: Metadata = {
  title: "Checkout",
  description: "Generated by create next app",
};

export default function CheckoutPageWrapper() {
  return (
    <Suspense fallback={<SuspenseLoader />}>
      <CheckoutPage />
    </Suspense>
  );
}
