import { Metadata } from "next";

import BreadCrumb from "@/components/BreadCrumb";
import HeadLine2 from "@/components/HeadLine2";
import WebpageWrapper from "@/components/wrapper/WebpageWrapper";
import { Suspense } from "react";
import SuspenseLoader from "@/components/SuspenseLoader";

// Metadata
export const metadata: Metadata = {
  title: "Differences between the JPT and JLPT",
  description: "Generated by create next app",
};

export default function DifferenceOfJPTandJLPT() {
  const breadCrumbData = [
    {
      name: "Home",
      to: "/",
    },
    {
      name: "Differences between the JPT and JLPT",
      to: "/differences_between_the_jpt_and_jlpt",
    },
  ];
  return (
    <Suspense fallback={<SuspenseLoader />}>
      <div className="pt-5">
        <WebpageWrapper>
          <BreadCrumb breadCrumbData={breadCrumbData} />
          <div className="sm:w-1/2 mt-5">
            <HeadLine2
              mainText="The JPT and JLPT"
              preText="Differences between"
              subText=""
            />
          </div>
          <div className="mt-10 pb-15">
            <h1 className="primary-text-color font-semibold text-2xl">
              Comparison Chart
            </h1>

            <table className="w-full border-separate border-spacing-0 rounded sm:rounded-xl overflow-hidden shadow-xl mt-6 text-sm bg-white">
              <thead>
                <tr className="bg-gradient-to-r from-blue-500 to-blue-700 text-white text-xs sm:text-base">
                  <th className="p-2 sm:p-5 text-left font-bold border-r border-gray-200">
                    Type
                  </th>
                  <th className="p-2 sm:p-5 text-left font-bold border-r border-gray-200">
                    JLPT
                  </th>
                  <th className="p-2 sm:p-5 text-left font-bold border-r border-gray-200">
                    JPT EL
                  </th>
                  <th className="p-2 sm:p-5 text-left font-bold">Comments</th>
                </tr>
              </thead>
              <tbody>
                <tr className="bg-gray-50 text-xs sm:text-base">
                  <td
                    className="p-2 sm:p-5 font-semibold text-blue-700 border-t border-r border-gray-200"
                    rowSpan={2}
                  >
                    Score
                  </td>
                  <td className="p-2 sm:p-5 text-gray-700 border-t border-r border-gray-200">
                    N4
                  </td>
                  <td className="p-2 sm:p-5 text-red-700 border-t border-r border-gray-200">
                    89+ points / 200
                  </td>
                  <td
                    className="p-2 sm:p-5 text-gray-700 border-t border-gray-200"
                    rowSpan={3}
                  >
                    <ul className="list-disc list-inside space-y-2 text-gray-700 text-sm">
                      <li>
                        <span className="font-medium text-blue-700">JLPT</span>{" "}
                        uses N1–N5 levels.
                      </li>
                      <li>
                        <span className="font-medium text-blue-700">JPT</span>{" "}
                        scores 10–200, like IELTS/GRE.
                      </li>
                      <li>
                        JPT ≥ <span className="font-medium">68</span> = JLPT N5
                        equivalent.
                      </li>
                      <li>
                        JPT evaluates{" "}
                        <span className="italic">actual skill growth</span>.
                      </li>
                      <li>JLPT: 2x/year, JPT: every month.</li>
                    </ul>
                  </td>
                </tr>
                <tr className="bg-gray-50 text-xs sm:text-base">
                  <td className="p-2 sm:p-5 text-gray-700 border-t border-r border-gray-200">
                    N5
                  </td>
                  <td className="p-2 sm:p-5 text-red-700 border-t border-r border-gray-200">
                    68+ points / 200
                  </td>
                </tr>
                <tr className="bg-gray-50 text-xs sm:text-base">
                  <td className="p-2 sm:p-5 font-semibold text-blue-700 border-t border-r border-gray-200">
                    Exam Time
                  </td>
                  <td className="p-2 sm:p-5 text-gray-700 border-t border-r border-gray-200">
                    Twice (July & Dec)
                  </td>
                  <td className="p-2 sm:p-5 text-gray-700 border-t border-r border-gray-200">
                    Monthly (Jan–Dec)
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </WebpageWrapper>
      </div>
    </Suspense>
  );
}
