import { Metadata } from "next";

import { Suspense } from "react";
import SuspenseLoader from "@/components/SuspenseLoader";
import RefundComponent from "./RefundComponent";

// Metadata
export const metadata: Metadata = {
  title: "Refund and Cancellation",
  description: "Generated by create next app",
};

export default function Refund() {
  return (
    <Suspense fallback={<SuspenseLoader />}>
      <RefundComponent />
    </Suspense>
  );
}
