import { Metadata } from "next";

import PhoneVerificationPage from "./optVerifyPage";
import { Suspense } from "react";
import SuspenseLoader from "@/components/SuspenseLoader";

// Metadata
export const metadata: Metadata = {
  title: "Otp Verify",
  description: "Generated by create next app",
};

export default function OtpVerifyPageWrapper() {
  return (
    <Suspense fallback={<SuspenseLoader />}>
      <PhoneVerificationPage />
    </Suspense>
  );
}
