import { Metadata } from "next";

import BreadCrumb from "@/components/BreadCrumb";
import HeadLine2 from "@/components/HeadLine2";
import WebpageWrapper from "@/components/wrapper/WebpageWrapper";
import SuspenseLoader from "@/components/SuspenseLoader";

import { FaPhoneAlt, FaEnvelope, FaMapMarkerAlt } from "react-icons/fa";
import { MdOutlineDocumentScanner } from "react-icons/md";

import Image from "next/image";
import { Suspense } from "react";


export const metadata: Metadata = {
  title: "About Us",
  description: "Generated by create next app",
};

export default function AboutUs() {
  const breadCrumbData = [
    { name: "Home", to: "/" },
    { name: "About Us", to: "/about_us" },
  ];

  return (
    <>
      <Suspense
        fallback={
          <SuspenseLoader/>
        }
      >
        <div className="space-y-15 pb-15 pt-5 relative overflow-clip">
          <div className="relative z-10">
            <WebpageWrapper>
              <BreadCrumb breadCrumbData={breadCrumbData} />
              <div className="mt-5 flex items-center">
                <div className="md:w-2/3 xl:w-1/2 h-fit md:bg-[#f6fafdf1] md:p-8 rounded-xl md:-mr-20 relative z-10 md:shadow-xl md:drop-shadow-md">
                  <HeadLine2
                    preText="See more Information"
                    mainText="About Us"
                    subText="Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsam placeat laborum ipsa. Accusamus illo voluptate dolorum error, explicabo non quasi."
                  />
                </div>
                <div className="hidden md:block w-full md:w-[700px] max-h-[60vh] overflow-hidden">
                  <Image
                    src="/assets/img/col-13.jpg"
                    width={512}
                    height={512}
                    alt=""
                    className="w-full max-h-[60vh] object-cover object-bottom"
                  />
                </div>
              </div>
              <div className="mt-16 p-5 sm:p-10 space-y-12 bg-[#ffffffc0] backdrop-blur-sm rounded-3xl shadow-2xl border border-gray-200">
                {/* Company Info */}
                <div className="space-y-5">
                  <h1 className="text-3xl font-extrabold bg-gradient-to-r from-blue-700 to-blue-400 text-transparent bg-clip-text">
                    Company Name
                  </h1>
                  <hr className="border-t-2 border-blue-300 w-20" />

                  <div className="flex items-start gap-3 text-gray-600">
                    <FaMapMarkerAlt className="mt-1 text-blue-500" />
                    <p>
                      House Name: A-SHA, House No: 2 E (2nd Floor),
                      <br />
                      Road: 8, Sector: 7, Uttara Model Town, Dhaka-1230
                    </p>
                  </div>
                  <div className="flex items-center gap-3 text-gray-600">
                    <FaPhoneAlt className="text-blue-500" />
                    <p>+880 1847 291881</p>
                  </div>
                  <div className="flex items-center gap-3 text-gray-600">
                    <FaEnvelope className="text-blue-500" />
                    <p className="break-all">
                      info@kaicomsol.com / abcd@gmail.com
                    </p>
                  </div>
                </div>

                {/* Aims */}
                <div className="space-y-4">
                  <h2 className="text-2xl font-semibold text-blue-700">
                    Our Aims
                  </h2>
                  <ul className="list-disc list-inside text-gray-700 space-y-2 pl-2">
                    {[
                      "Spread the Japanese language and culture across Bangladesh.",
                      "Expand institutions capable of teaching Japanese language.",
                      "Evaluate Japanese language skills in Bangladesh.",
                      "Promote business relationships between Japan and Bangladesh.",
                    ].map((item, index) => (
                      <li
                        key={index}
                        className="hover:translate-x-1 transition-transform duration-200 ease-in-out"
                      >
                        {item}
                      </li>
                    ))}
                  </ul>
                </div>

                {/* Executive Officer */}
                <div className="space-y-3">
                  <h2 className="text-2xl font-semibold text-blue-700">
                    Executive Officer
                  </h2>
                  <p className="text-gray-800 text-lg font-medium">
                    CEO: Anjan Das
                  </p>
                </div>

                {/* Exam Executives */}
                <div className="space-y-3">
                  <h2 className="text-2xl font-semibold text-blue-700">
                    Exam Executives
                  </h2>
                  <ul className="text-gray-700 text-base space-y-1 pl-1">
                    <li className="hover:pl-1 hover:text-blue-600 transition-all">
                      Anik Sarkar
                    </li>
                    <li className="hover:pl-1 hover:text-blue-600 transition-all">
                      Shuvodip Mondal
                    </li>
                  </ul>
                </div>

                {/* Button */}
                <div className="pt-4">
                  <button className="group flex items-center gap-2 px-8 py-3 bg-gradient-to-r from-blue-700 to-blue-500 hover:from-blue-900 hover:to-blue-700 transition-all duration-300 text-white sm:text-lg sm:font-semibold rounded-full shadow-lg hover:shadow-xl">
                    <MdOutlineDocumentScanner className="hidden sm:inline-flex sm:text-2xl group-hover:rotate-6 transition-transform" />
                    Company Authorization Documents
                  </button>
                </div>
              </div>
            </WebpageWrapper>
          </div>

          <Image
            src="/assets/img/overlay-6.png"
            width={612}
            height={408}
            alt=""
            className="absolute -top-20 left-150 size-36"
          />

          <Image
            src="/assets/img/overlay-10.png"
            width={612}
            height={408}
            alt=""
            className="absolute top-0 right-0 size-20"
            // style={{ animationDelay: "0.5s" }}
          />

          <Image
            src="/assets/img/overlay-4.png"
            width={612}
            height={408}
            alt=""
            className="absolute top-150 right-30 size-20"
          />

          <Image
            src="/assets/img/overlay-8.png"
            width={612}
            height={408}
            alt=""
            className="absolute left-90 top-120 size-10"
          />
          <Image
            src="/assets/img/overlay-11.png"
            width={612}
            height={408}
            alt=""
            className="absolute left-1/2 top-1/2 rotate-45 size-20"
          />
          <Image
            src="/assets/img/overlay-5.png"
            width={612}
            height={408}
            alt=""
            className="absolute bottom-1/2 -left-30 size-56"
          />
          <Image
            src="/assets/img/overlay-9.png"
            width={612}
            height={408}
            alt=""
            className="absolute bottom-0 -right-40 size-86 opacity-35"
          />
        </div>
      </Suspense>
    </>
  );
}
