import { Metadata } from "next";

import { Suspense } from "react";
import LoginPage from "./signInPage";
import SuspenseLoader from "@/components/SuspenseLoader";

// Metadata
export const metadata: Metadata = {
  title: "Sign In",
  description: "Generated by create next app",
};

export default function SignInPageWrapper() {
  return (
    <Suspense fallback={<SuspenseLoader/>}>
      <LoginPage />
    </Suspense>
  );
}
