import BreadCrumb from "@/components/BreadCrumb";
import HeadLine2 from "@/components/HeadLine2";
import SuspenseLoader from "@/components/SuspenseLoader";
import WebpageWrapper from "@/components/wrapper/WebpageWrapper";
import { Suspense } from "react";

// Metadata
export const metadata = {
  title: "Score Descriptions",
  description: "Generated by create next app",
};

export default function ScoreDescription() {
  const breadCrumbData = [
    {
      name: "Home",
      to: "/",
    },
    {
      name: "Score Descriptions",
      to: "/score_descriptions",
    },
  ];
  return (
    <Suspense fallback={<SuspenseLoader />}>
      <div className="pt-5">
        <WebpageWrapper>
          <BreadCrumb breadCrumbData={breadCrumbData} />
          <div className="sm:w-1/2 mt-5">
            <HeadLine2 mainText="Score Descriptions" preText="JPT" subText="" />
          </div>
          <div className="mt-10 pb-16">
            <h1 className="text-2xl font-bold primary-text-color mb-6">
              JPT EL Score and Linguistic Competence
            </h1>

            <div className="overflow-x-auto rounded sm:rounded-2xl shadow-xl">
              <table className="min-w-full bg-white text-sm rounded sm:rounded-2xl">
                <thead>
                  <tr className="bg-gradient-to-r from-blue-700 to-blue-900 text-white text-xs sm:text-base">
                    <th className="px-2 py-2 sm:px-6 sm:py-4 text-left font-semibold border-r border-blue-300">
                      Score
                    </th>
                    <th className="px-2 py-2 sm:px-6 sm:py-4 text-left font-semibold border-r border-blue-300">
                      Listening comprehension
                    </th>
                    <th className="px-2 py-2 sm:px-6 sm:py-4 text-left font-semibold">
                      Reading comprehension
                    </th>
                  </tr>
                </thead>
                <tbody>
                  <tr className="bg-blue-50 text-xs sm:text-base">
                    <td
                      className="px-2 py-2 sm:px-6 sm:py-4 font-semibold text-blue-700 border-t border-r border-gray-200"
                      colSpan="3"
                    >
                      Simple content can be handled, but there is a problem in
                      accurate representation.
                    </td>
                  </tr>

                  <tr className="hover:bg-gray-100  transition text-xs sm:text-base">
                    <td className="px-2 py-2 sm:px-6 sm:py-4 font-semibold text-blue-700 border-t border-r border-gray-200">
                      Points 89 or above
                    </td>
                    <td className="px-2 py-2 sm:px-6 sm:py-4 text-gray-700 border-t border-r border-gray-200 space-y-2">
                      <ul className="list-disc pl-5 space-y-1">
                        <li>Able to understand easy daily conversations.</li>
                        <li>
                          Able to express easy Japanese about hobbies, families,
                          weather, or general topics.
                        </li>
                        <li>
                          Able to make a simple introduction about certain
                          topics relating to yourself.
                        </li>
                      </ul>
                    </td>
                    <td className="px-2 py-2 sm:px-6 sm:py-4 text-gray-700 border-t border-gray-200">
                      <ul className="list-disc pl-5 space-y-1">
                        <li>
                          Able to understand simple instructions and writings.
                        </li>
                        <li>
                          Incapable of finding necessary materials or documents,
                          and composing sentences.
                        </li>
                        <li>
                          Need to study more vocabulary, grammar, and Kanji.
                        </li>
                      </ul>
                    </td>
                  </tr>

                  <tr className="bg-blue-50 text-xs sm:text-base">
                    <td
                      className="px-2 py-2 sm:px-6 sm:py-4 font-semibold text-blue-700 border-t border-r border-gray-200"
                      colSpan="3"
                    >
                      Beginner communication skills and basic greetings and
                      self-introduction.
                    </td>
                  </tr>

                  <tr className="hover:bg-gray-100 transition text-xs sm:text-base">
                    <td className="px-2 py-2 sm:px-6 sm:py-4 font-semibold text-blue-700 border-t border-r border-gray-200">
                      Points 68 or above
                    </td>
                    <td className="px-2 py-2 sm:px-6 sm:py-4 text-gray-700  border-t border-r border-gray-200">
                      <ul className="list-disc pl-5 space-y-1">
                        <li>
                          Understand topics like hobbies, families, if spoken
                          slowly.
                        </li>
                        <li>
                          Make basic greetings at beginning or end of
                          conversations.
                        </li>
                        <li>Speak about own daily life easily.</li>
                      </ul>
                    </td>
                    <td className="px-2 py-2 sm:px-6 sm:py-4 text-gray-700 border-t border-gray-200">
                      <ul className="list-disc pl-5 space-y-1">
                        <li>Only recognize basic and easy phrases.</li>
                        <li>Know fragments of Japanese.</li>
                        <li>Understand simple notes.</li>
                      </ul>
                    </td>
                  </tr>

                  <tr className="bg-blue-50 text-xs sm:text-base">
                    <td
                      className="px-2 py-2 sm:px-6 sm:py-4 font-semibold text-blue-700 border-t border-r border-gray-200"
                      colSpan="3"
                    >
                      Incapable of having communications or reading in Japanese.
                    </td>
                  </tr>

                  <tr className="hover:bg-gray-100 transition text-xs sm:text-base">
                    <td className="px-2 py-2 sm:px-6 sm:py-4 font-semibold text-blue-700 border-t border-r border-gray-200">
                      Below 68 points
                    </td>
                    <td
                      className="px-2 py-2 sm:px-6 sm:py-4 text-red-700 border-t border-r border-gray-200"
                      colSpan="2"
                    >
                      Incapable of having communications or reading in Japanese.
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>

            <p className="mt-10 text-xs text-gray-500 italic">
              *According to a CEFR correlation survey (Dec 2020), the standard
              level for Japanese has been raised from 68 to 89.
            </p>
          </div>
        </WebpageWrapper>
      </div>
    </Suspense>
  );
}
